#!/usr/bin/env bashio

export DSMRREADER_DATALOGGER_INPUT_METHOD=$(bashio::config 'DSMRREADER_DATALOGGER_INPUT_METHOD')
export DSMRREADER_DATALOGGER_API_HOSTS=$(bashio::config 'DSMRREADER_DATALOGGER_API_HOSTS')
export DSMRREADER_DATALOGGER_API_KEYS=$(bashio::config 'DSMRREADER_DATALOGGER_API_KEYS')
export DSMRREADER_DATALOGGER_SERIAL_PORT=$(bashio::config 'DSMRREADER_DATALOGGER_SERIAL_PORT')
export DSMRREADER_DATALOGGER_SERIAL_BAUDRATE=$(bashio::config 'DSMRREADER_DATALOGGER_SERIAL_BAUDRATE')
export DSMRREADER_DATALOGGER_SERIAL_BYTESIZE=$(bashio::config 'DSMRREADER_DATALOGGER_SERIAL_BYTESIZE')
export DSMRREADER_DATALOGGER_SERIAL_PARITY=$(bashio::config 'DSMRREADER_DATALOGGER_SERIAL_PARITY')
export DSMRREADER_DATALOGGER_SLEEP=$(bashio::config 'DSMRREADER_DATALOGGER_SLEEP')

python ./dsmr_datalogger_api_client.py