#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------------------------------------
# HOMEASSISTANT Add-On OVERRIDES
#---------------------------------------------------------------------------------------------------------------------------
function _info() { printf "\\r[ \\033[00;34mINFO\\033[0m ] %s\\n" "$@"; }
CONFIG_PATH=/data/options.json
if [ -z "${DJANGO_DATABASE_HOST}" ] || [ "${DJANGO_DATABASE_HOST}" == 'dsmrdb' ]; then
  _info ${DJANGO_DATABASE_HOST}
  _info "ENV's being updated"
  export DSMRREADER_ADMIN_USER=$(jq --raw-output '.DSMRREADER_ADMIN_USER' $CONFIG_PATH)
  export DSMRREADER_ADMIN_PASSWORD=$(jq --raw-output '.DSMRREADER_ADMIN_PASSWORD' $CONFIG_PATH)
  export DJANGO_DATABASE_NAME=$(jq --raw-output '.DJANGO_DATABASE_NAME' $CONFIG_PATH)
  export DJANGO_DATABASE_USER=$(jq --raw-output '.DJANGO_DATABASE_USER' $CONFIG_PATH)
  export DJANGO_DATABASE_PASSWORD=$(jq --raw-output '.DJANGO_DATABASE_PASSWORD' $CONFIG_PATH)
  export DJANGO_DATABASE_HOST=$(jq --raw-output '.DJANGO_DATABASE_HOST' $CONFIG_PATH)
  export DJANGO_DATABASE_PORT=$(jq --raw-output '.DJANGO_DATABASE_PORT' $CONFIG_PATH)
  export DATALOGGER_MODE=$(jq --raw-output '.DATALOGGER_MODE' $CONFIG_PATH)
  export DATALOGGER_SERIAL_PORT=$(jq --raw-output '.DATALOGGER_SERIAL_PORT' $CONFIG_PATH)
  export DATALOGGER_INPUT_METHOD=$(jq --raw-output '.DATALOGGER_INPUT_METHOD' $CONFIG_PATH)
  export DATALOGGER_SERIAL_BAUDRATE=$(jq --raw-output '.DATALOGGER_SERIAL_BAUDRATE' $CONFIG_PATH)
  export DATALOGGER_NETWORK_HOST=$(jq --raw-output '.DATALOGGER_NETWORK_HOST' $CONFIG_PATH)
  export DATALOGGER_NETWORK_PORT=$(jq --raw-output '.DATALOGGER_NETWORK_PORT' $CONFIG_PATH)
  export DATALOGGER_SLEEP=$(jq --raw-output '.DATALOGGER_SLEEP' $CONFIG_PATH)
  export DSMRREADER_LOGLEVEL=$(jq --raw-output '.DSMRREADER_LOGLEVEL' $CONFIG_PATH)
  export ENABLE_IFRAME='true'
fi

if [[ "${DATALOGGER_MODE}" = standalone || "${DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - backend..."
    cd /app || exit
    exec s6-setuidgid app /usr/local/bin/python3 -u /app/manage.py dsmr_backend
fi
